Repository flant/shell-operator, pull requests merged in 2023-05, with the labels that each got.

#483 Add healthz handler
  examples/204-validating-webhook/templates/deployment.yaml
  examples/206-mutating-webhook/templates/deployment.yaml
  examples/210-conversion-webhook/templates/deployment.yaml
  pkg/webhook/admission/handler.go
  pkg/webhook/admission/handler_test.go
  pkg/webhook/conversion/handler.go
Labels: go

#489 links to HOOKS.md after move in e5da08d19823c872af8b4aad6448c7073d48c117
  README.md
  examples/220-execution-rate/README.md
Labels: bug

#491 Adding single line output for base64
  examples/206-mutating-webhook/hooks/mutating.sh
Labels: bug

#496 Fix GitHub Actions warnings
  .github/workflows/docs.yaml
Labels: dependencies, github_actions

#497 chore(go): Fix race conditions
  pkg/kube_events_manager/kube_events_manager.go
  pkg/task/queue/queue_set.go
  test/integration/kubeclient/kube_client_test.go
Labels: bug, go
