Repository flant/shell-operator, pull requests merged in 2023-10, with the labels that each got.

#538 add IgnoreHookError patch option
  pkg/kube/object_patch/operation.go
  pkg/kube/object_patch/options.go
  pkg/kube/object_patch/patch.go
  pkg/kube/object_patch/patch_collector.go
  pkg/kube/object_patch/validation.go
  pkg/shell-operator/operator.go
Labels: enhancement

#536 Refactor internals. Make the operator more lib-oriented
  .github/workflows/lint.yaml
  .github/workflows/tests-labeled.yaml
  .golangci.yaml
  go.mod
  go.sum
  pkg/app/app.go
  pkg/debug/server.go
  pkg/hook/config/util.go
  pkg/hook/controller/hook_controller_test.go
  pkg/hook/hook.go
  pkg/hook/hook_manager.go
  pkg/hook/hook_manager_test.go
  pkg/hook/task_metadata/task_metadata_test.go
  pkg/kube_events_manager/error_handler.go
  pkg/kube_events_manager/factory.go
  pkg/kube_events_manager/filter.go
  pkg/kube_events_manager/filter_test.go
  pkg/kube_events_manager/kube_events_manager.go
  pkg/kube_events_manager/kube_events_manager_test.go
  pkg/kube_events_manager/monitor.go
  pkg/kube_events_manager/monitor_config.go
  pkg/kube_events_manager/monitor_test.go
  pkg/kube_events_manager/namespace_informer.go
  pkg/kube_events_manager/resource_informer.go
  pkg/kube_events_manager/types/types.go
  pkg/kube_events_manager/util.go
  pkg/kube_events_manager/util_test.go
  pkg/metric_storage/metric_storage.go
  pkg/schedule_manager/schedule_manager.go
  pkg/schedule_manager/schedule_manager_test.go
  pkg/shell-operator/bootstrap.go
  pkg/shell-operator/combine_binding_context.go
  pkg/shell-operator/combine_binding_context_test.go
  pkg/shell-operator/debug_server.go
  pkg/shell-operator/http_server.go
  pkg/shell-operator/kube_client.go
  pkg/shell-operator/manager_events_handler.go
  pkg/shell-operator/metrics_hooks.go
  pkg/shell-operator/metrics_operator.go
  pkg/shell-operator/operator.go
  pkg/shell-operator/operator_test.go
  pkg/task/dump/dump.go
  pkg/task/queue/task_queue_test.go
  pkg/task/task.go
  pkg/utils/file/dir.go
  pkg/utils/file/file.go
  pkg/utils/labels/labels.go
  pkg/webhook/admission/manager.go
  pkg/webhook/admission/manager_test.go
  pkg/webhook/admission/resource.go
  pkg/webhook/conversion/crd_client_config.go
  pkg/webhook/conversion/manager.go
  pkg/webhook/validating/validation/rule.go
  pkg/webhook/validating/validation/validation.go
  test/hook/context/context_combiner.go
  test/hook/context/generator.go
  test/integration/kube_event_manager/kube_event_manager_test.go
  test/integration/kubeclient/object_patch_test.go
  test/integration/suite/run.go
Labels: enhancement, go

#541 Handle empty config hook section
  pkg/hook/hook_manager.go
Labels: bug, go

#540 Update kube client
  go.mod
  go.sum
Labels: enhancement, dependencies

#544 Ignore some file extensions
  pkg/utils/file/file.go
Labels: enhancement, go

#549 Separate metric storages
  pkg/hook/controller/kubernetes_bindings_controller.go
  pkg/shell-operator/bootstrap.go
  pkg/shell-operator/http_server.go
  pkg/shell-operator/metrics_hooks.go
  pkg/shell-operator/metrics_operator.go
  pkg/shell-operator/operator.go
Labels: enhancement, go
