Repository flant/shell-operator, pull requests merged in 2024-10, with the labels that each got.

#665 fix shell_lib regarding grouping
  frameworks/shell/hook.sh
  pkg/hook/binding_context/binding_context.go
  pkg/hook/binding_context/binding_context_test.go
Labels: bug

#661 Metric storage mock
  .dockerignore
  .gitignore
  go.mod
  go.sum
  pkg/metric/collector.go
  pkg/metric/collector_test.go
  pkg/metric/grouped_storage_mock.go
  pkg/metric/storage.go
  pkg/metric/storage_mock.go
  pkg/metric/storage_test.go
  pkg/metric_storage/metric_storage.go
  pkg/metric_storage/vault/vault.go
  pkg/metric_storage/vault/vault_test.go
Labels: go, release-note/ignore

#666 [schedule-manager] fix entry clean-up
  pkg/schedule_manager/schedule_manager.go
Labels: bug

#669 Update go.mod
  go.mod
Labels: bug, go

#674 [shell-operator] Fix logrus leak
  pkg/executor/executor.go
Labels: bug, go
