Repository flant/shell-operator, pull requests merged in 2024-09, with the labels that each got.

#654 refactor conversion webhook
  pkg/app/webhook.go
  pkg/hook/binding_context/binding_context.go
  pkg/hook/controller/conversion_bindings_controller.go
  pkg/hook/controller/hook_controller.go
  pkg/hook/hook.go
  pkg/hook/hook_manager.go
  pkg/hook/hook_manager_test.go
  pkg/metric_storage/vault/collector.go
  pkg/shell-operator/bootstrap.go
  pkg/shell-operator/operator.go
  pkg/utils/file/file.go
  pkg/utils/file/file_test.go
  pkg/webhook/conversion/event.go
  pkg/webhook/conversion/handler.go
  pkg/webhook/conversion/manager.go
  pkg/webhook/conversion/response.go
  test/hook/context/context_combiner.go
  test/hook/context/generator.go
Labels: enhancement, go, dev-image/publish/amd64-only

#656 Refactor admission webhook
  pkg/hook/controller/admission_bindings_controller.go
  pkg/hook/controller/hook_controller.go
  pkg/hook/hook.go
  pkg/hook/hook_manager.go
  pkg/hook/hook_manager_test.go
  pkg/shell-operator/operator.go
  pkg/webhook/admission/event.go
  pkg/webhook/admission/handler.go
  pkg/webhook/admission/manager.go
  pkg/webhook/admission/response.go
  pkg/webhook/admission/response_test.go
  pkg/webhook/admission/testdata/response/good_allow.json
  pkg/webhook/admission/testdata/response/good_allow_warnings.json
  pkg/webhook/admission/testdata/response/good_deny.json
  pkg/webhook/admission/testdata/response/good_deny_quiet.json
Labels: enhancement, go

#655 [kube-event-manager] fix factory context issue
  pkg/kube_events_manager/factory.go
  pkg/kube_events_manager/resource_informer.go
Labels: bug

#657 add GetFailureMessage method
  pkg/task/task.go
Labels: enhancement

#659 Refactor task and task-metadata
  pkg/hook/task_metadata/task_metadata.go
  pkg/shell-operator/operator.go
  pkg/task/task.go
Labels: enhancement, go
