Repository flant/shell-operator, pull requests merged in 2024-12, with the labels that each got.

#693 Fix/rollback keep tmp files
  pkg/app/debug.go
  pkg/hook/hook.go
Labels: bug

#694 Feat/executor json log
  go.mod
  go.sum
  pkg/config/config.go
  pkg/executor/executor.go
  pkg/executor/executor_test.go
  pkg/shell-operator/bootstrap.go
  pkg/webhook/admission/handler.go
  pkg/webhook/conversion/handler.go
Labels: bug, enhancement

#703 [ci] add nonamedreturns linter
  .golangci.yaml
  pkg/debug/server.go
  pkg/filter/jq/jq_exec.go
  pkg/hook/config/config_v0.go
  pkg/hook/config/config_v1.go
  pkg/hook/config/validator.go
  pkg/hook/config/versioned_untyped.go
  pkg/hook/hook.go
  pkg/hook/hook_manager.go
  pkg/hook/task_metadata/task_metadata.go
  pkg/kube/object_patch/helpers.go
  pkg/kube/object_patch/patch.go
  pkg/kube/object_patch/validation.go
  pkg/kube_events_manager/filter_test.go
  pkg/kube_events_manager/monitor.go
  pkg/kube_events_manager/monitor_config.go
  pkg/kube_events_manager/resource_informer.go
  pkg/shell-operator/bootstrap.go
  pkg/shell-operator/operator.go
  pkg/task/queue/task_queue.go
  pkg/task/queue/task_queue_test.go
  pkg/utils/file/dir.go
  pkg/webhook/admission/handler.go
  test/utils/directory.go
  test/utils/jsonloganalyzer.go
  test/utils/prometheus.go
  test/utils/shell-operator.go
Labels: enhancement

#702 replace deprecated logger methods
  .golangci.yaml
  pkg/app/log.go
  pkg/debug/server.go
  pkg/executor/executor.go
  pkg/executor/executor_test.go
  pkg/hook/binding_context/binding_context.go
  pkg/hook/controller/admission_bindings_controller.go
  pkg/hook/controller/conversion_bindings_controller.go
  pkg/hook/controller/kubernetes_bindings_controller.go
  pkg/hook/hook_manager.go
  pkg/hook/task_metadata/task_metadata.go
  pkg/kube/object_patch/operation.go
  pkg/kube/object_patch/patch.go
  pkg/kube_events_manager/error_handler.go
  pkg/kube_events_manager/factory.go
  pkg/kube_events_manager/kube_events_manager.go
  pkg/kube_events_manager/monitor.go
  pkg/kube_events_manager/namespace_informer.go
  pkg/kube_events_manager/resource_informer.go
  pkg/kube_events_manager/types/types.go
  pkg/metric_storage/metric_storage.go
  pkg/metric_storage/vault/vault.go
  pkg/schedule_manager/schedule_manager.go
  pkg/shell-operator/combine_binding_context.go
  pkg/shell-operator/http_server.go
  pkg/shell-operator/manager_events_handler.go
  pkg/shell-operator/operator.go
  pkg/task/queue/task_queue.go
  pkg/utils/file/file.go
  pkg/utils/file/file_test.go
  pkg/utils/signal/signal.go
  pkg/webhook/admission/handler.go
  pkg/webhook/admission/resource.go
  pkg/webhook/conversion/handler.go
  pkg/webhook/server/server.go
Labels: enhancement, go
