Repository flant/shell-operator, pull requests merged in 2025-04, with the labels that each got.

#747 fix: data races
  .github/workflows/tests.yaml
  pkg/hook/controller/kubernetes_bindings_controller.go
  pkg/hook/controller/schedule_bindings_controller.go
  pkg/kube_events_manager/factory.go
  pkg/kube_events_manager/monitor.go
  pkg/kube_events_manager/monitor_test.go
  pkg/schedule_manager/schedule_manager.go
  test/hook/context/generator.go
Labels: enhancement, go

#749 chore(deps): update Go version and bump kube-client
  go.mod
  go.sum
Labels: dependencies, go

#753 [debug] add watch to queue list
  go.mod
  go.sum
  pkg/debug/debug-cmd.go
Labels: enhancement

#735 [shell-operator] feat/new operator event handling mechanism
  pkg/hook/controller/hook_controller.go
  pkg/hook/hook_manager.go
  pkg/shell-operator/operator.go
Labels: enhancement

#755 [chore] bump module sdk
  go.mod
  go.sum
Labels: dependencies, dev-image/publish/amd64-only

#759 fix: restore integration tests
  .github/workflows/tests-labeled.yaml
  go.mod
  go.sum
  pkg/kube_events_manager/kube_events_manager.go
  test/integration/kube_event_manager/kube_event_manager_test.go
  test/integration/kubeclient/kube_client_test.go
  test/integration/kubeclient/object_patch_test.go
  test/integration/suite/run.go
  test/utils/kubectl.go
  test/utils/streamedexec.go
  tools/ginkgo.go
Labels: dependencies, github_actions

#756 fix: restore jqFilters
  .github/workflows/tests-labeled.yaml
  Dockerfile
  go.mod
  go.sum
  pkg/filter/filter.go
  pkg/filter/jq/apply.go
  pkg/filter/jq/apply_test.go
  pkg/kube/object_patch/helpers.go
  pkg/kube_events_manager/filter.go
  pkg/kube_events_manager/kube_events_manager.go
  test/integration/kube_event_manager/kube_event_manager_test.go
  test/integration/kubeclient/kube_client_test.go
  test/integration/kubeclient/object_patch_test.go
  test/integration/suite/run.go
  test/utils/kubectl.go
  test/utils/streamedexec.go
  tools/ginkgo.go
Labels: bug, go, dev-image/publish/amd64-only
